---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: centos-5.9
  - name: centos-6.4

suites:
  - name: default
    run_list: recipe[cookbook-ruby_app::default]
    attributes:
