---
language: ruby
rvm:
  - 1.9.3
cache:
  - bundler
bundler_args: --without integration
before_script: bundle exec berks install
script: bundle exec strainer test --strainer-file=ci/Strainerfile
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - jeremy.olliver@gmail.com
