source 'https://rubygems.org'

gem 'berkshelf'
gem 'strainer', '~> 3.3.0'
gem 'chef', '~> 11.8.0'
gem 'rubocop', '~> 0.16.0'
gem 'foodcritic', '~> 3.0.0'
gem 'chefspec', '~> 3.1.4'
gem 'serverspec', '~> 0.14.2'
gem 'test-kitchen'
gem 'kitchen-vagrant'
