source 'https://rubygems.org'

gem 'berkshelf',  '~> 2.0'
gem 'strainer',   '~> 3.3.0'
gem 'chef',       "~> 11.10.0.rc.0" # need json 1.8 #'~> 11.8.0'
gem 'rubocop',    '~> 0.17.0'
gem 'foodcritic', '~> 3.0.0'
gem 'chefspec',   '~> 3.1.4'
gem 'serverspec', '~> 0.14.2'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'cane'
